apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: node-learn
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: node-learn-questions
